first commit (ajout formulaire d'ajout d'items)
cesar-richard/pumpkin pull request #18
Opened 2023-03-13 14:30 UTC by leochapp

2023-03-15 09:09 UTC, mael-belval commented on backend/backend/settings.py
> +TIME_ZONE = 'UTC'
fr-FR UTC+1 ?

2023-03-15 09:55 UTC, mael-belval requested changes
- **gitignore .idea stp**
- Pour une V0, pourquoi 15 migrations ? Migrations serait pas plutôt pour des evol de BDD sur les MAJ futurs ?
- Pas fan du franglais

2023-03-15 10:03 UTC, cesar-richard commented on backend/backend/settings.py
> +TIME_ZONE = 'UTC'
On a vu ca ensemble en off déjà pour les 3 points cités, le franglais va partir en english, le .gitignore va etre pimpé et les 15migs vont etre squashed en 1

2023-03-15 10:08 UTC, mael-belval commented
L'arbo est pas clair aussi

- backend
  - backend => backend/backend ? L'arrière de l'arrière c'est l'avant ?
  - pumpkin => Vu que sous-dossier migrations, pumpkin c'est de la logique métier ou la persistence ?
    - migrations

2023-03-15 13:09 UTC, cesar-richard requested changes

2023-03-15 13:09 UTC, cesar-richard commented on backend/pumpkin/migrations/0010_alter_item_creation_date_alter_item_date_achat_and_more.py
> +            field=models.DateField(default='2023-03-13'),
La date en dur ca va pas, faut que tu defaults sur NOW()

2023-03-15 13:09 UTC, cesar-richard commented on backend/pumpkin/migrations/0010_alter_item_creation_date_alter_item_date_achat_and_more.py
> +            field=models.DateField(default='2023-03-13'),
Meme commentaire sur le default

2023-03-15 13:09 UTC, cesar-richard commented on backend/pumpkin/views.py
> +        #return Response({'message': 'Requête POST traitée avec succès'})
```suggestion

```

Si c'est pas utile (surtout si c'est du debug) ca ne doit pas monter dans la PR

2023-03-15 13:09 UTC, cesar-richard commented on backend/pumpkin/models.py
> +    updated_date = models.DateField(default=datetime.today().strftime('%Y-%m-%d'))
```suggestion
    creation_date = models.DateField(auto_now_add=True)
    updated_date = models.DateField(auto_now=True)
```

La correction des defaults dont je parle dans les migrations peut se résoudre simplement comme ca.
Ce que tu as ecrit comme code est évaluer au moment de générer la migration et est donc "en dur". Ces options la sont au contraire prévues pour passer le "NOW()" aux bons endroits

2023-03-18 18:41 UTC, cesar-richard commented
Le commit de node_modules 😭

2023-03-18 19:49 UTC, mael-belval requested changes
- Éviter le CSS inline
- Élément type les couleurs dans le CSS, en faire des variables

2023-03-18 19:49 UTC, mael-belval commented on backend/config/settings.py
> +>>>>>>> 9ebd61aa (Structure cleanup):backend/config/settings.py
Conflit à resolve

2023-03-18 19:49 UTC, mael-belval commented on backend/pumpkin/__pycache__/__init__.cpython-310.pyc
a suppr

2023-03-18 19:49 UTC, mael-belval commented on backend/pumpkin/__pycache__/admin.cpython-310.pyc
a suppr

2023-03-18 19:49 UTC, mael-belval commented on backend/pumpkin/__pycache__/apps.cpython-310.pyc
a suppr

2023-03-18 19:49 UTC, mael-belval commented on backend/pumpkin/__pycache__/models.cpython-310.pyc
a suppr

2023-03-18 19:49 UTC, mael-belval commented on backend/pumpkin/__pycache__/serializers.cpython-310.pyc
a suppr

2023-03-18 19:49 UTC, mael-belval commented on backend/pumpkin/__pycache__/views.cpython-310.pyc
a suppr

2023-03-18 19:49 UTC, mael-belval commented on frontend/node_modules/postcss-initial/~/.config/configstore/update-notifier-npm.json
a suppr ?

2023-03-18 19:49 UTC, mael-belval commented on frontend/package.json
> +    "axios": "^0.21.1",
Pourquoi axios ?

2023-03-18 19:49 UTC, mael-belval commented on frontend/package.json
> +    "bootstrap": "^4.6.0",
Pourquoi bootstrap si material ui ?

2023-03-18 19:49 UTC, mael-belval commented on frontend/package.json
> +    "moment": "^2.29.4",
Moment est mort, pourquoi moment ? https://momentjs.com/docs/#/-project-status/

2023-03-18 19:49 UTC, mael-belval commented on frontend/public/logo192.png
a suppr

2023-03-18 19:49 UTC, mael-belval commented on frontend/public/logo512.png
a suppr

2023-03-18 19:49 UTC, mael-belval commented on frontend/public/index.html
> +    <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
Vraiment besoin de faire une PWA ?

2023-03-18 19:49 UTC, mael-belval commented on frontend/public/manifest.json
Même question PWA

2023-03-18 19:49 UTC, mael-belval commented on frontend/src/components/ContainerAligned.js
> +  <div>
Besoin du div ? On peut return direct le container si pas d'apport graphique

2023-03-18 19:49 UTC, mael-belval commented on frontend/src/components/Form.js
> +      .post("http://localhost:8000/api/items/", {nom, reference, etat, commentaire, quantite, date_achat: date_achat!==""?date_achat:null})
Pourquoi axios ? fetch fait le taf ici

2023-03-18 19:49 UTC, mael-belval commented on frontend/src/components/Form.js
> +import 'semantic-ui-css/semantic.min.css'
Pourquoi ?

2023-03-18 19:49 UTC, mael-belval commented on frontend/src/components/Form.js
> +]
indent

2023-03-18 19:49 UTC, mael-belval commented on frontend/src/components/Form.js
> +            <Form.Input fluid label="Date d'achat" type='date' max={moment().format('YYYY-MM-DD')} onChange={event => setDate_achat(event.target.value)} value={date_achat}/>
date-fns pour remplacer moment ?

2023-03-18 19:49 UTC, mael-belval commented on frontend/src/components/Form.js
> +function FormItem() {
arrow function pour l'homogénéité

2023-03-18 19:49 UTC, mael-belval commented on frontend/src/components/Header.js
> +export default class MenuBar extends Component {
Passer en functional component

2023-03-18 19:49 UTC, mael-belval commented on frontend/src/components/Header.js
> +  handleItemClick = (e, { name }) => this.setState({ activeItem: name })
useState

2023-03-18 19:49 UTC, mael-belval commented on frontend/src/components/ContainerAligned.js
> +import React from 'react'
Pas besoin depuis react 17 de l'importer

2023-03-18 19:49 UTC, mael-belval commented on frontend/src/components/Form.js
> +import React, {Component, useState} from 'react'
Pas besoin depuis react 17 de l'importer

2023-03-18 19:49 UTC, mael-belval commented on frontend/src/components/Header.js
> +import React, { Component } from 'react'
Pas besoin depuis react 17 de l'importer

2023-03-18 19:49 UTC, mael-belval commented on frontend/src/components/HomePage.js
> +import React from 'react'
Pas besoin depuis react 17 de l'importer

2023-03-18 19:49 UTC, mael-belval commented on frontend/src/components/HomePageComponents/FinalContainerHomePage.js
> +import React from 'react'
Pas besoin depuis react 17 de l'importer

2023-03-18 19:49 UTC, mael-belval commented on frontend/src/components/HomePageComponents/FinalContainerHomePage.js
> +    <p>mabite</p>
il manque un espace :troll:

2023-03-18 19:49 UTC, mael-belval commented on frontend/src/components/HomePageComponents/HomePageStackable.js
> +import React from 'react'
Pas besoin depuis react 17 de l'importer

2023-03-18 19:49 UTC, mael-belval commented on frontend/src/components/HomePageComponents/HomePageText.js
> +import React from 'react'
Pas besoin depuis react 17 de l'importer

2023-03-18 19:49 UTC, mael-belval commented on frontend/src/components/HomePageComponents/LoginButton.js
> +import React from 'react'
Pas besoin depuis react 17 de l'importer

2023-03-18 19:49 UTC, mael-belval commented on frontend/src/components/HomePageComponents/LoginButton.js
> +  <div>
Besoin du div ?

2023-03-18 19:49 UTC, mael-belval commented on frontend/src/index.js
> +import 'bootstrap/dist/css/bootstrap.css';
Pourquoi ?

2023-03-18 19:49 UTC, mael-belval commented on frontend/src/pages/Home.jsx
> +        <div>
nav

2023-03-18 19:49 UTC, mael-belval commented on frontend/src/pages/Home.jsx
> +    <div>
Besoin de ce div ?

2023-03-18 19:49 UTC, mael-belval commented on frontend/src/pages/Home.jsx
> +        <div>
main

2023-03-18 20:08 UTC, leochapp commented on backend/pumpkin/views.py
> +        #return Response({'message': 'Requête POST traitée avec succès'})
oupsi

2023-03-28 10:57 UTC, leochapp commented on backend/pumpkin/migrations/0010_alter_item_creation_date_alter_item_date_achat_and_more.py
> +            field=models.DateField(default='2023-03-13'),
c'était pr un test, normalement c'est fix

2023-03-28 11:02 UTC, leochapp commented on frontend/src/components/HomePageComponents/LoginButton.js
> +  <div>
c'est suppr, effectivement, ça sert à rien

2023-03-28 11:02 UTC, leochapp commented on frontend/src/index.js
> +import 'bootstrap/dist/css/bootstrap.css';
bootstrap et l'import de react ça dégage

2023-03-28 11:04 UTC, leochapp commented on frontend/src/pages/Home.jsx
> +        <div>
done

2023-03-28 11:04 UTC, leochapp commented on frontend/src/pages/Home.jsx
> +        <div>
c'est à dire ?

2023-03-28 11:05 UTC, leochapp commented on backend/pumpkin/models.py
> +        ACCEPTABLE = 4,"Acceptable"
done

2023-03-28 13:19 UTC, mael-belval commented on frontend/src/pages/Home.jsx
> +        <div>
<main> au lieu de <div> pour le contenu principal

2023-03-29 08:01 UTC, mael-belval commented on frontend/src/pages/Home.jsx
> +        <div>
Tiens, je vois que les balises sont pas passés.
Je disais : au lieu de `<div>`
pour le contenu principal `<main>`

2023-03-29 08:06 UTC, mael-belval commented on frontend/src/pages/Home.jsx
> +    </nav>
HomePage dans la navigation ?
```suggestion
    <nav>
        <MenuBar/>
    </nav>
    <main>
        <HomePage/>
    </main>
```

2023-03-29 08:06 UTC, mael-belval commented on frontend/src/components/HomePageComponents/LoginButton.js
> +    <Button style={{textAlign:'right'}} color={"orange"}>Login</Button>
Passe le string color directement, pas besoin de l'évaluer inutilement. (et toujours, essaye d'éviter les styles inlines, comme pour ton text align)
```suggestion
    <Button style={{textAlign:'right'}} color="orange">Login</Button>
```

2023-03-29 08:12 UTC, mael-belval commented on frontend/src/pages/Home.jsx
> +    </nav>
kdo: https://developer.mozilla.org/en-US/docs/Glossary/Semantics#semantic_elements

2023-03-31 06:14 UTC, leochapp commented on frontend/src/pages/Home.jsx
> +    </nav>
merciiii

2023-03-31 06:15 UTC, leochapp commented
On est bons pour le first commit ?

2023-03-31 08:22 UTC, cesar-richard requested changes

2023-03-31 08:22 UTC, cesar-richard commented on .env
> +REDIRECT_URI: http://localhost:8000/oauth
Faut pas commit ton .env
A la limite tu fais un .env.defaults avec des valeurs d'exemple MAIS PAS DES VRAIS TRUCS

2023-03-31 08:22 UTC, cesar-richard commented on backend/config/settings.py
> +LANGUAGE_CODE = 'en-us'
```suggestion
LANGUAGE_CODE = 'fr-fr'
```

2023-03-31 08:22 UTC, cesar-richard commented on backend/config/settings.py
> +    'redirect_uri': REDIRECT_URI,                               # adresse de callback
```suggestion
    'client_id': os.environ['CLIENT_ID'], # ID du client OAuth
    'client_secret': os.environ['CLIENT_SECRET'], # Secret du client OAuth
    'authorization_url': os.environ['AUTHORIZATION_URL'], # lien d'autorisation OAuth sur le PDA
    'token_url': os.environ['TOKEN_URL'], # lien de récupération des tokens sur le PDA
    'redirect_uri': os.environ['REDIRECT_URI'], # adresse de callback
```

Ne mets qu'un espace avant tes inline comments (c'est conventionnel)
Et ne créé pas de variable qui ne servent qu'a donner une valeur a une autre variable. Lis directement le env ici.

2023-03-31 08:22 UTC, cesar-richard commented on backend/config/settings.py
> +REDIRECT_URI = os.environ['REDIRECT_URI']
```suggestion
```
Ces variables sont inutiles, je t'explique dans le bloc oauth pourquoi

2023-03-31 08:22 UTC, cesar-richard commented on backend/config/urls.py
> +"""
```suggestion
```
Un peu de nettoyage des commentaires inutiles

2023-03-31 08:22 UTC, cesar-richard commented on backend/pumpkin/__pycache__/__init__.cpython-310.pyc
Vire le __pycache__ de ton commit

2023-03-31 08:22 UTC, cesar-richard commented on frontend/node_modules/postcss-initial/~/.config/configstore/update-notifier-npm.json
vire le node_modules de ton commit

2023-03-31 08:22 UTC, cesar-richard commented on frontend/public/logo192.png
Tu te sers de ces logos ? sinon dégage les

2023-03-31 08:22 UTC, cesar-richard commented on frontend/public/logo512.png
A virer aussi si tu t'en sers pas

2023-03-31 08:22 UTC, cesar-richard commented on frontend/src/components/Form.js
> +]
Je vais caler un petit linter un pre-commit hook soon

2023-03-31 09:35 UTC, mael-belval commented on frontend/src/pages/Home.jsx
> +function Home() {
arrow function plutôt (const Home...)

2023-03-31 09:49 UTC, mael-belval commented on frontend/public/manifest.json
Si tu suppr les logos react, a suppr, ou ajouter des logos types SiMDE si tu veux "installer" l'app sur mobile (raccourci)

2023-03-31 09:49 UTC, mael-belval commented on frontend/src/App.test.js
Je pense que le test passe pas

2023-03-31 09:49 UTC, mael-belval commented on frontend/src/components/CurrentDate.js
?

2023-03-31 09:49 UTC, mael-belval commented on frontend/src/components/HomePage.js
> +  <div>
Pourquoi div ? Un fragment (<></>) ferait pas l'affaire ?

2023-03-31 09:49 UTC, mael-belval commented on frontend/src/components/HomePageComponents/FinalContainerHomePage.js
> +  <Container style={{marginTop:'3%'}} text>
Avoid inline css

2023-03-31 09:49 UTC, mael-belval commented on frontend/src/components/HomePageComponents/LoginButton.js
> +    <Button style={{textAlign:'right'}} color="orange">Login</Button>
avoid inline css

2023-03-31 09:49 UTC, mael-belval commented on frontend/src/style/Home.css
> +    background-color: #1b1c1d;
Fait de tes couleurs des variables sur :root (plutôt sur index.css le :root)

```CSS
:root {
    --background-color: #1b1c1d;
}
```

Usage:
`background-color: var(--background-color)`

2023-03-31 16:24 UTC, leochapp commented on frontend/src/pages/Home.jsx
> +function Home() {
conf eslint -> tout passé en function

2023-03-31 16:43 UTC, leochapp commented on frontend/src/App.test.js
?

2023-04-03 17:23 UTC, mael-belval reviewed
ça deviens bon!

2023-04-03 17:23 UTC, mael-belval commented on frontend/node_modules/postcss-initial/~/.config/configstore/update-notifier-npm.json
Toujours à suppr

2023-04-03 17:23 UTC, mael-belval commented on frontend/package.json
> +    "axios": "^0.21.1",
toujours axios à retirer

2023-04-03 17:23 UTC, mael-belval commented on frontend/package.json
> +    "moment": "^2.29.4",
toujours moment à retirer

2023-04-03 17:23 UTC, mael-belval commented on frontend/public/favicon.ico
a suppr/remplacer par un logo simde ou autre

2023-04-03 17:23 UTC, mael-belval commented on frontend/public/logo192.png
a suppr/remplacer par un logo simde ou autre

2023-04-03 17:23 UTC, mael-belval commented on frontend/public/logo512.png
a suppr/remplacer par un logo simde ou autre

2023-04-03 17:23 UTC, mael-belval commented on frontend/src/App.test.jsx
test à corriger

2023-04-03 17:23 UTC, mael-belval commented on frontend/src/components/ContainerAligned.jsx
> +      {' '}
pourquoi ?

2023-04-03 17:23 UTC, mael-belval commented on frontend/src/components/Form.jsx
> +      });
Utiliser fetch

2023-04-03 17:23 UTC, mael-belval commented on frontend/src/components/Form.jsx
> +        <Form.Input fluid label="Date d'achat" type="date" max={moment().format('YYYY-MM-DD')} onChange={(event) => setDateAchat(event.target.value)} value={dateAchat} />
virer moment, pour date-fns par exemple

2023-04-03 17:23 UTC, mael-belval commented on frontend/src/components/HomePage.jsx
> +    <div>
div ou fragment ici ?

2023-04-03 17:23 UTC, mael-belval commented on frontend/src/components/HomePage.jsx
> +        <Header style={{ color: 'white' }} size="medium">Gestion de l&apos;inventaire des associations.</Header>
style inline

2023-04-03 17:23 UTC, mael-belval commented on frontend/src/components/HomePageComponents/HomePageText.jsx
> +      <Header as="h1">Prêts de matériel</Header>
Deux h1 dans la même page pas autorisé. Remplace tes h1 par des h2 ici ? (pour garder un style cohérent entre les deux)

2023-05-05 16:14 UTC, mael-belval commented
100

2023-05-25 06:44 UTC, closed without merging